development:
  adapter: postgresql
  encoding: unicode
  database: cakedb
  pool: 2
  username: nico
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: cakedb
  pool: 2
  username: nico
  password: password
