development:
  adapter: postgresql
  encoding: unicode
  database: cakedb
  pool: 2
  username: nico
  password: password
  host: ENV['DATABASE_URL']
production:
  adapter: postgresql
  encoding: unicode
  database: cakedb
  pool: 2
  username: nico
  password: password
  host: ENV['DATABASE_URL']
